//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit
    {
        public int id { get; set; }
        public string operation { get; set; }
        public string utilisateur { get; set; }
        public Nullable<int> refeclient { get; set; }
        public Nullable<double> montantfacture { get; set; }
        public Nullable<double> montantencaissement { get; set; }
        public Nullable<double> anciensolde { get; set; }
        public Nullable<double> soldeclient { get; set; }
        public Nullable<System.DateTime> dateoperation { get; set; }
        public Nullable<int> codevillage { get; set; }
        public Nullable<int> ancienetat { get; set; }
        public Nullable<int> nouveletat { get; set; }
    }
}
