//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class AXEMT
    {
        public string codeMT { get; set; }
        public string NomAXE { get; set; }
        public Nullable<double> @long { get; set; }
        public System.Data.Entity.Spatial.DbGeography geom { get; set; }
    }
}
