//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class bordereaux
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bordereaux()
        {
            this.encaissements = new HashSet<encaissements>();
        }
    
        public int id { get; set; }
        public string numero { get; set; }
        public Nullable<System.DateTime> datecreation { get; set; }
        public Nullable<double> montant { get; set; }
        public Nullable<byte> ouvert { get; set; }
        public string utilisateur { get; set; }
        public Nullable<System.DateTime> datevalidation { get; set; }
        public string type { get; set; }
        public string validateur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encaissements> encaissements { get; set; }
    }
}
