//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class changementinterface
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string oldinterface { get; set; }
        public string newinterface { get; set; }
        public Nullable<int> indexdepose { get; set; }
        public Nullable<int> indexpose { get; set; }
        public string utilisateur { get; set; }
        public Nullable<int> refclient { get; set; }
    }
}
