//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class communes
    {
        public int id { get; set; }
        public string nom { get; set; }
        public int code_com { get; set; }
        public System.Data.Entity.Spatial.DbGeography geom { get; set; }
        public int iddepartement { get; set; }
    
        public virtual departements departements { get; set; }
    }
}
