//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class compteurs
    {
        public int id { get; set; }
        public string numerointerface { get; set; }
        public Nullable<System.DateTime> datereception { get; set; }
        public string utilisateur { get; set; }
        public Nullable<byte> libre { get; set; }
        public string type { get; set; }
        public Nullable<int> entrepot { get; set; }
        public string fabricant { get; set; }
    }
}
