//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class cust_sandbox
    {
        public int N_ { get; set; }
        public Nullable<int> ID1 { get; set; }
        public Nullable<double> ID { get; set; }
        public string Nom1 { get; set; }
        public string Prenom { get; set; }
        public string Num_ID { get; set; }
        public string Tel { get; set; }
        public string Raison_Social { get; set; }
        public string Usage { get; set; }
        public string Date_Abonnement { get; set; }
        public string Village { get; set; }
        public string Region { get; set; }
        public string Departement { get; set; }
        public string Commune { get; set; }
        public string Niv_Service { get; set; }
        public string Type_Elect { get; set; }
        public string TypeBranch { get; set; }
        public string calibre { get; set; }
        public string FraisAbonn { get; set; }
        public int Reference_Contrat { get; set; }
        public Nullable<double> Montant_Encaisse { get; set; }
        public string Solde { get; set; }
        public string Frais_NET { get; set; }
        public string Etat_Client { get; set; }
        public string Commentaire { get; set; }
        public string Evolution_Statut { get; set; }
        public string Date_Mise_en_Service { get; set; }
        public string Date_Resiliation { get; set; }
        public string X_GPS { get; set; }
        public string Y_GPS { get; set; }
        public string Bordereau { get; set; }
        public string Contrat { get; set; }
        public string @interface { get; set; }
        public string Ancien_indexe { get; set; }
        public string Arriere { get; set; }
        public string Penalite { get; set; }
        public string MoisEnCours { get; set; }
        public double SoldeTotal { get; set; }
        public string ModeFacturation { get; set; }
        public Nullable<double> Encaissement { get; set; }
        public string DateEncaissement { get; set; }
        public string IDPayment { get; set; }
        public string Prev_Bill { get; set; }
        public string Last_Bill { get; set; }
        public string NbrEP { get; set; }
        public string Type_de_contenu { get; set; }
        public string Application_créée_par { get; set; }
        public string Application_modifiée_par { get; set; }
        public string Pièces_jointes { get; set; }
        public string ID_de_l_instance_du_flux_de_travail { get; set; }
        public string Type_de_fichier { get; set; }
        public string Modifié { get; set; }
        public string Créé { get; set; }
        public string Créé_par { get; set; }
        public string Modifié_par { get; set; }
        public string Chemin_d_URL { get; set; }
        public string Chemin_d_accès { get; set; }
        public string Type_d_élément { get; set; }
        public string URL_absolue_codée { get; set; }
        public Nullable<double> index { get; set; }
        public string dateReleve { get; set; }
        public Nullable<double> NewIndex { get; set; }
        public string periodeFacturee { get; set; }
        public string dateCoupure { get; set; }
        public Nullable<System.DateTime> dateAbonn { get; set; }
        public Nullable<System.DateTime> dateMeS { get; set; }
        public string idlastbill { get; set; }
        public string NivPuissance { get; set; }
    }
}
