//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class encaissementsreport
    {
        public string Nom1 { get; set; }
        public string Prenom { get; set; }
        public string nom { get; set; }
        public string nom_region { get; set; }
        public string nomcommune { get; set; }
        public string village { get; set; }
        public Nullable<int> netPayer { get; set; }
        public double SoldeTotal { get; set; }
        public string PeriodeFacturee { get; set; }
        public string numero { get; set; }
        public Nullable<double> montantencaisee { get; set; }
        public Nullable<System.DateTime> dateencaissement { get; set; }
        public Nullable<int> idfacture { get; set; }
        public Nullable<int> refclient { get; set; }
        public Nullable<int> codevillage { get; set; }
        public Nullable<double> penalite { get; set; }
        public Nullable<System.DateTime> datenecaisse { get; set; }
        public string utilisateur { get; set; }
        public string numerorecue { get; set; }
    }
}
