//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class encaissement
    {
        public string Idpayment { get; set; }
        public Nullable<System.DateTime> DatePaiement { get; set; }
        public Nullable<double> MontantEncaisse { get; set; }
        public string SoldeAnterieur { get; set; }
        public string SoldePostPay { get; set; }
        public string Idclient { get; set; }
        public string idFacture { get; set; }
        public string Commentaire { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string village { get; set; }
        public string nivserv { get; set; }
        public string periodefacture { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public int id { get; set; }
        public Nullable<double> fraiscoupure { get; set; }
    }
}
