//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class encaissements
    {
        public int id { get; set; }
        public Nullable<int> idfacture { get; set; }
        public Nullable<int> refclient { get; set; }
        public Nullable<double> montantencaisee { get; set; }
        public Nullable<double> soldeprepaiement { get; set; }
        public Nullable<double> soldepostpaiement { get; set; }
        public Nullable<System.DateTime> dateencaissement { get; set; }
        public string utilisateur { get; set; }
        public string commentaire { get; set; }
        public Nullable<int> idbordereau { get; set; }
        public string numerorecue { get; set; }
    
        public virtual bordereaux bordereaux { get; set; }
    }
}
