//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class factures
    {
        public int id { get; set; }
        public Nullable<int> idreleve { get; set; }
        public string dateReleve { get; set; }
        public Nullable<double> conso { get; set; }
        public Nullable<double> RedTableau { get; set; }
        public Nullable<double> PartEnergetique { get; set; }
        public Nullable<double> Red_electRural { get; set; }
        public Nullable<double> assTVA { get; set; }
        public Nullable<double> TVA { get; set; }
        public Nullable<int> netPayer { get; set; }
        public Nullable<double> TCO { get; set; }
        public Nullable<double> AncienIndex { get; set; }
        public Nullable<double> NouvIndex { get; set; }
        public string PeriodeFacturee { get; set; }
        public Nullable<double> ReportArr { get; set; }
        public string IdFacture { get; set; }
        public Nullable<double> solde { get; set; }
        public Nullable<double> penalite { get; set; }
        public Nullable<int> RefClient { get; set; }
        public byte Paiement { get; set; }
        public Nullable<int> NbreJours { get; set; }
        public Nullable<double> fraiscoupure { get; set; }
        public string datesysteme { get; set; }
    }
}
