//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class mevlist
    {
        public Nullable<System.DateTime> dateMeV { get; set; }
        public string numbord { get; set; }
        public Nullable<int> montantbord { get; set; }
        public string iduser { get; set; }
        public int id { get; set; }
        public string remarque { get; set; }
    }
}
