//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class migration
    {
        public int id { get; set; }
        public Nullable<int> anciennivpui { get; set; }
        public Nullable<int> nouveaunivpui { get; set; }
        public Nullable<double> frais { get; set; }
        public Nullable<int> referenceclient { get; set; }
        public Nullable<System.DateTime> datemigration { get; set; }
        public string @interface { get; set; }
        public string index { get; set; }
    
        public virtual clients clients { get; set; }
    }
}
