//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class MisEnServiceVillages
    {
        public int ID_SERVICE { get; set; }
        public string REGION { get; set; }
        public string DEPARTEMENT { get; set; }
        public string COMMUNE { get; set; }
        public string VILLAGE { get; set; }
        public string dateRaccPremierClient { get; set; }
        public string Etat_travaux { get; set; }
        public Nullable<int> code_village { get; set; }
        public Nullable<int> CapaciteTransformateur { get; set; }
        public Nullable<int> PuissanceDHP { get; set; }
        public Nullable<int> nombreSupport { get; set; }
        public Nullable<double> LineaireBT { get; set; }
        public Nullable<System.DateTime> datemiseenservice { get; set; }
    
        public virtual villages villages { get; set; }
    }
}
