//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class near_dist
    {
        public int id { get; set; }
        public Nullable<int> codevillage { get; set; }
        public string near_dist1 { get; set; }
        public string axe { get; set; }
        public string code { get; set; }
    
        public virtual villages villages { get; set; }
    }
}
