//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class programmes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public programmes()
        {
            this.villages = new HashSet<villages>();
        }
    
        public string nom { get; set; }
        public int ID { get; set; }
        public string tech { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<int> delai { get; set; }
        public Nullable<int> budget { get; set; }
        public Nullable<int> MTavance { get; set; }
        public Nullable<double> niveau_decaissement { get; set; }
        public string avenant { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string descriptProg { get; set; }
        public string remarque { get; set; }
        public string operateur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<villages> villages { get; set; }
    }
}
