//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class reclamation
    {
        public int id { get; set; }
        public Nullable<int> refclient { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> type { get; set; }
        public string priorite { get; set; }
        public string commentaire { get; set; }
        public string nivintervention { get; set; }
        public string telephone { get; set; }
        public Nullable<int> localite { get; set; }
        public string statut { get; set; }
        public string utilisateur { get; set; }
        public string numcompteur { get; set; }
        public Nullable<System.DateTime> datecloture { get; set; }
        public string nature { get; set; }
    
        public virtual typereclamation typereclamation { get; set; }
        public virtual clients clients { get; set; }
    }
}
