//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class recouvrements
    {
        public int id { get; set; }
        public Nullable<System.DateTime> opendate { get; set; }
        public Nullable<System.DateTime> closedate { get; set; }
        public string periode { get; set; }
        public string utilisateur { get; set; }
        public Nullable<double> montantRecouvre { get; set; }
        public string nbrFactures { get; set; }
        public string nbrFacturesPayees { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<byte> facturee { get; set; }
    }
}
