//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class references
    {
        public int id { get; set; }
        public string refclient { get; set; }
        public string numcompteur { get; set; }
        public Nullable<System.DateTime> datepose { get; set; }
        public Nullable<int> indexpose { get; set; }
        public Nullable<System.DateTime> datedepose { get; set; }
        public Nullable<byte> pose { get; set; }
        public Nullable<int> indexdepose { get; set; }
        public string technicien { get; set; }
    }
}
