//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class releves
    {
        public int ID { get; set; }
        public Nullable<int> Reference_Contrat { get; set; }
        public string numcompteur { get; set; }
        public Nullable<int> Ancien_index { get; set; }
        public Nullable<int> Nouvel_index { get; set; }
        public Nullable<double> consommation { get; set; }
        public string date_de_relève { get; set; }
        public string nom1 { get; set; }
        public string prenom { get; set; }
        public string village { get; set; }
        public string commune { get; set; }
        public string periode { get; set; }
        public string prevbill { get; set; }
        public string nivpuissance { get; set; }
        public Nullable<int> nbreJour { get; set; }
        public string departement { get; set; }
        public string region { get; set; }
        public string categorie { get; set; }
        public string nivservice { get; set; }
        public Nullable<byte> facturee { get; set; }
        public byte[] remarque { get; set; }
    
        public virtual clients clients { get; set; }
    }
}
