//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class resiliation
    {
        public int id { get; set; }
        public Nullable<int> refclient { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string utilisateur { get; set; }
        public string commentaire { get; set; }
        public Nullable<int> motif { get; set; }
        public Nullable<double> netapayer { get; set; }
        public Nullable<int> indexdepose { get; set; }
        public string @interface { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual motifresiliation motifresiliation { get; set; }
    }
}
