//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAV
    {
        public int id { get; set; }
        public Nullable<int> REFERENCE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string VILLAGE { get; set; }
        public string OLDETAT { get; set; }
        public string NEWETAT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string ACTION { get; set; }
        public string MOTIF { get; set; }
        public string REMARQUE { get; set; }
        public string PERIODE { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> index { get; set; }
        public string periodedue { get; set; }
    }
}
