//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempReleves
    {
        public int id { get; set; }
        public Nullable<int> ReferenceContrat { get; set; }
        public string numcompteur { get; set; }
        public Nullable<int> Ancienindex { get; set; }
        public Nullable<int> Nouvelindex { get; set; }
        public Nullable<int> consommation { get; set; }
        public string datereleve { get; set; }
        public string periode { get; set; }
        public Nullable<int> nombrejours { get; set; }
        public string type { get; set; }
    }
}
