//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DetailsEncaissement
    {
        public int id { get; set; }
        public Nullable<double> sommeenc { get; set; }
        public Nullable<int> nbrenc { get; set; }
        public Nullable<double> montant { get; set; }
        public string numero { get; set; }
        public string utilisateur { get; set; }
        public string datecreation { get; set; }
    }
}
