//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class villages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public villages()
        {
            this.MisEnServiceVillages = new HashSet<MisEnServiceVillages>();
            this.near_dist = new HashSet<near_dist>();
        }
    
        public int id { get; set; }
        public string region { get; set; }
        public string departement { get; set; }
        public string commune { get; set; }
        public string village { get; set; }
        public Nullable<int> population { get; set; }
        public Nullable<double> menage { get; set; }
        public string education { get; set; }
        public string sante { get; set; }
        public string forage { get; set; }
        public string antenne_bts { get; set; }
        public string moulin { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public int code_village { get; set; }
        public Nullable<int> code_prog { get; set; }
        public Nullable<int> idLocalite { get; set; }
        public string etattravaux { get; set; }
        public Nullable<int> technologie { get; set; }
        public Nullable<byte> commercialise { get; set; }
        public Nullable<int> nbrclients { get; set; }
        public string codemt { get; set; }
        public Nullable<double> neardist { get; set; }
        public string source { get; set; }
    
        public virtual communes communes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MisEnServiceVillages> MisEnServiceVillages { get; set; }
        public virtual programmes programmes { get; set; }
        public virtual Technologies Technologies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<near_dist> near_dist { get; set; }
    }
}
