//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class villages
    {
        public int id { get; set; }
        public string region { get; set; }
        public string departement { get; set; }
        public string commune { get; set; }
        public string village { get; set; }
        public Nullable<int> population { get; set; }
        public Nullable<double> menage { get; set; }
        public Nullable<byte> education { get; set; }
        public Nullable<byte> sante { get; set; }
        public Nullable<byte> forage { get; set; }
        public Nullable<byte> antenne_bts { get; set; }
        public Nullable<byte> moulin { get; set; }
        public Nullable<double> @long { get; set; }
        public Nullable<double> lat { get; set; }
        public int code_village { get; set; }
        public Nullable<int> code_prog { get; set; }
        public Nullable<int> idLocalite { get; set; }
    }
}
