//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proera
{
    using System;
    using System.Collections.Generic;
    
    public partial class village
    {
        public string localite { get; set; }
        public int id_localite { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<int> pop { get; set; }
        public Nullable<int> menage { get; set; }
        public Nullable<int> forage { get; set; }
        public Nullable<int> ecole { get; set; }
        public Nullable<int> sante { get; set; }
        public Nullable<int> gsm { get; set; }
        public Nullable<int> autreprod { get; set; }
        public string code_MT { get; set; }
        public string etat { get; set; }
        public Nullable<double> Near_dist { get; set; }
        public Nullable<int> id_prog { get; set; }
        public System.Data.Entity.Spatial.DbGeography geom { get; set; }
    }
}
